// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftr071wyrCqsjUuzxNjCO3f4hIiEaXuE',
    appId: '1:333990912437:web:c0ca942e9048ac73fc39fc',
    messagingSenderId: '333990912437',
    projectId: 'campuseats-d1b26',
    authDomain: 'campuseats-d1b26.firebaseapp.com',
    storageBucket: 'campuseats-d1b26.firebasestorage.app',
    measurementId: 'G-YGNDD870FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiX8AxJVd0vbkp8YSkmrPl3LblWZXwoPQ',
    appId: '1:333990912437:android:ff5556baba955588fc39fc',
    messagingSenderId: '333990912437',
    projectId: 'campuseats-d1b26',
    storageBucket: 'campuseats-d1b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMI3Tcfa-mBcENSjqCrWFcTS0B9QV-iA8',
    appId: '1:333990912437:ios:1ae775c32cfc476cfc39fc',
    messagingSenderId: '333990912437',
    projectId: 'campuseats-d1b26',
    storageBucket: 'campuseats-d1b26.firebasestorage.app',
    iosBundleId: 'com.example.campuseats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMI3Tcfa-mBcENSjqCrWFcTS0B9QV-iA8',
    appId: '1:333990912437:ios:1ae775c32cfc476cfc39fc',
    messagingSenderId: '333990912437',
    projectId: 'campuseats-d1b26',
    storageBucket: 'campuseats-d1b26.firebasestorage.app',
    iosBundleId: 'com.example.campuseats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDftr071wyrCqsjUuzxNjCO3f4hIiEaXuE',
    appId: '1:333990912437:web:a0088d0812bbbe1dfc39fc',
    messagingSenderId: '333990912437',
    projectId: 'campuseats-d1b26',
    authDomain: 'campuseats-d1b26.firebaseapp.com',
    storageBucket: 'campuseats-d1b26.firebasestorage.app',
    measurementId: 'G-SF1BDXR75V',
  );
}
