// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04cw2GiTg2UTG54cBlvDJVvHidxt_guY',
    appId: '1:1012043856028:web:14334cf1c9aaefc6859559',
    messagingSenderId: '1012043856028',
    projectId: 'finance-project-f1d0e',
    authDomain: 'finance-project-f1d0e.firebaseapp.com',
    storageBucket: 'finance-project-f1d0e.firebasestorage.app',
    measurementId: 'G-QXLH15VPZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVfO_AqatLBBu1pAsFMCL7UbsRzAl98fA',
    appId: '1:1012043856028:android:9391910aebaf87e6859559',
    messagingSenderId: '1012043856028',
    projectId: 'finance-project-f1d0e',
    storageBucket: 'finance-project-f1d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGi8_uowIofMA1l_quH84XaFo6RfBxDus',
    appId: '1:1012043856028:ios:ed9de8c7c387ebeb859559',
    messagingSenderId: '1012043856028',
    projectId: 'finance-project-f1d0e',
    storageBucket: 'finance-project-f1d0e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGi8_uowIofMA1l_quH84XaFo6RfBxDus',
    appId: '1:1012043856028:ios:ed9de8c7c387ebeb859559',
    messagingSenderId: '1012043856028',
    projectId: 'finance-project-f1d0e',
    storageBucket: 'finance-project-f1d0e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04cw2GiTg2UTG54cBlvDJVvHidxt_guY',
    appId: '1:1012043856028:web:88ffe00c92e69934859559',
    messagingSenderId: '1012043856028',
    projectId: 'finance-project-f1d0e',
    authDomain: 'finance-project-f1d0e.firebaseapp.com',
    storageBucket: 'finance-project-f1d0e.firebasestorage.app',
    measurementId: 'G-TMKKM50PS2',
  );
}
