// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IK5vlGXheASb5bXhT7Aba3pWkGWmAe0',
    appId: '1:289269349302:web:c164ddc26713f2fe429f17',
    messagingSenderId: '289269349302',
    projectId: 'campusconnect-fa9ba',
    authDomain: 'campusconnect-fa9ba.firebaseapp.com',
    storageBucket: 'campusconnect-fa9ba.firebasestorage.app',
    measurementId: 'G-ETD3N6SMD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSw5DAIplNEyFXpf97r2CdoHmfUD0k5no',
    appId: '1:289269349302:android:ae0c13c312471832429f17',
    messagingSenderId: '289269349302',
    projectId: 'campusconnect-fa9ba',
    storageBucket: 'campusconnect-fa9ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzd_neBihrSMUaeBLGKl1IFUA7B4HdAN4',
    appId: '1:289269349302:ios:117e69a4a54e804b429f17',
    messagingSenderId: '289269349302',
    projectId: 'campusconnect-fa9ba',
    storageBucket: 'campusconnect-fa9ba.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzd_neBihrSMUaeBLGKl1IFUA7B4HdAN4',
    appId: '1:289269349302:ios:117e69a4a54e804b429f17',
    messagingSenderId: '289269349302',
    projectId: 'campusconnect-fa9ba',
    storageBucket: 'campusconnect-fa9ba.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0IK5vlGXheASb5bXhT7Aba3pWkGWmAe0',
    appId: '1:289269349302:web:de72fa2a02384ce0429f17',
    messagingSenderId: '289269349302',
    projectId: 'campusconnect-fa9ba',
    authDomain: 'campusconnect-fa9ba.firebaseapp.com',
    storageBucket: 'campusconnect-fa9ba.firebasestorage.app',
    measurementId: 'G-GV1M8DG1TR',
  );
}
