// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKcziWKFzS8fj_HzFxAt_TRPk2CiyTW4',
    appId: '1:422987249082:web:fd93d650a1834269a85983',
    messagingSenderId: '422987249082',
    projectId: 'midsemfirebase',
    authDomain: 'midsemfirebase.firebaseapp.com',
    storageBucket: 'midsemfirebase.firebasestorage.app',
    measurementId: 'G-VML7FJREG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Cf0HI8KRiehTZH2-N-8N1HuXABaWb7w',
    appId: '1:422987249082:android:b799759b9513b044a85983',
    messagingSenderId: '422987249082',
    projectId: 'midsemfirebase',
    storageBucket: 'midsemfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoe1HvcZIULz8Oso3ZLwVYwwiiGaR4Nc',
    appId: '1:422987249082:ios:053557de336e98c1a85983',
    messagingSenderId: '422987249082',
    projectId: 'midsemfirebase',
    storageBucket: 'midsemfirebase.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoe1HvcZIULz8Oso3ZLwVYwwiiGaR4Nc',
    appId: '1:422987249082:ios:053557de336e98c1a85983',
    messagingSenderId: '422987249082',
    projectId: 'midsemfirebase',
    storageBucket: 'midsemfirebase.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZKcziWKFzS8fj_HzFxAt_TRPk2CiyTW4',
    appId: '1:422987249082:web:14b4ddba850c8f2fa85983',
    messagingSenderId: '422987249082',
    projectId: 'midsemfirebase',
    authDomain: 'midsemfirebase.firebaseapp.com',
    storageBucket: 'midsemfirebase.firebasestorage.app',
    measurementId: 'G-GK6ZB59NLY',
  );
}
